### ISSUE TITLE
[Feat]: Multiple cam request

### ISSUE THREAD

**Issue by emirbeytekin** [apivideo/api.video-swift-live-stream#14]
### Version

last

### Environment that reproduces the issue

iphone 15 pro

### Use case description

Thanks for the sample application, when starting live broadcast; How can I start with the rear camera turned on?

**Comment by emirbeytekin** [comment]
<img width="1071" alt="image" src="https://github.com/apivideo/api.video-swift-live-stream/assets/13369070/31e0d1ca-bb13-46d2-bf52-769a63ddaa1c">
ah, sorry my bad
I want to start broadcasting with my rear and front cameras open at the same time like this iamge

**Comment by ThibaultBee** [comment]
It is not supported and we don't have plan for this.
You should directly use HaishinKit (the engine behind this project).
